version: "3"
services:
  app:
    build: docker/php
    volumes:
      - ./app:/app
    depends_on:
      - rmq
      - db

  rmq:
    build:
      context: docker/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: nginx:1.12-alpine
    ports:
      - 80:80
    volumes:
      - ./app:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app